version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: file-storage_bd
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: files
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres