name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  BACKEND_TAG: gustosilva/file-storage-api:latest

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: maven

      - name: Up database
        run: docker compose up -d

      - name: Run Tests
        run: mvn -B clean test

      - name: Down database
        run: docker compose down

  docker-build-and-push:
    name: Docker - Build and push
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: maven

      - name: Generate jar
        run: mvn -B clean package -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.API_TAG }}

  docker-sync:
    name: Docker sync
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker sync
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{env.DOCKERHUB_TOKEN}}
          repository: gustosilva/dsvendas-backend-java
          readme: "./README.md"
